services:
  mysql:
    image: mysql:8.4
    container_name: mysql8
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

  postgres:
    image: postgres:18-alpine
    container_name: postgres18
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:7-alpine
    container_name: redis7
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redis_data:/data
    restart: always

volumes:
  mysql_data:
  postgres_data:
  redis_data:
